/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Course_Management_System;

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kaush
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    addWindowListener(new ExitConfirmationWindowListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FYP = new javax.swing.JPanel();
        FYP_label = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        wlvIcon = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        Reset_button = new javax.swing.JButton();
        email_label1 = new javax.swing.JLabel();
        signup_label = new javax.swing.JLabel();
        wlv3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1034, 562));
        setPreferredSize(new java.awt.Dimension(1034, 558));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        FYP.setBackground(new java.awt.Color(255, 255, 255));
        FYP.setMinimumSize(new java.awt.Dimension(600, 562));
        FYP.setPreferredSize(new java.awt.Dimension(400, 558));

        FYP_label.setBackground(new java.awt.Color(255, 255, 255));
        FYP_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        FYP_label.setText("Forgot Your Password?");

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        p1.setText("If you have forgotten your password, please enter your account's");

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        p2.setText("email address below and click the \"Reset My Password\" button.");

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        p3.setText("You will receive an email that contains a link to set a new password.");

        wlvIcon.setBackground(new java.awt.Color(255, 255, 255));
        wlvIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/wlv_logo__1_-removebg-preview.png"))); // NOI18N
        wlvIcon.setMaximumSize(new java.awt.Dimension(500, 40));

        email_label.setBackground(new java.awt.Color(255, 255, 255));
        email_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        email_label.setText("Email Address");

        email_textfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        Reset_button.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Reset_button.setText("Send Reset Instructions");
        Reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_buttonActionPerformed(evt);
            }
        });

        email_label1.setBackground(new java.awt.Color(255, 255, 255));
        email_label1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        email_label1.setText("Not a member?");

        signup_label.setBackground(new java.awt.Color(255, 255, 255));
        signup_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        signup_label.setForeground(new java.awt.Color(0, 120, 215));
        signup_label.setText("Sign up now");
        signup_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signup_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FYPLayout = new javax.swing.GroupLayout(FYP);
        FYP.setLayout(FYPLayout);
        FYPLayout.setHorizontalGroup(
            FYPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FYPLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(FYPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FYPLayout.createSequentialGroup()
                        .addGroup(FYPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p3)
                            .addComponent(FYP_label, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FYPLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(wlvIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FYPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(email_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signup_label)
                .addGap(27, 27, 27))
        );
        FYPLayout.setVerticalGroup(
            FYPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FYPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FYPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label1)
                    .addComponent(signup_label))
                .addGap(58, 58, 58)
                .addComponent(wlvIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FYP_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3)
                .addGap(56, 56, 56)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(FYP);

        wlv3.setBackground(new java.awt.Color(255, 255, 255));
        wlv3.setPreferredSize(new java.awt.Dimension(145, 558));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/we back you 2.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(385, 558));

        javax.swing.GroupLayout wlv3Layout = new javax.swing.GroupLayout(wlv3);
        wlv3.setLayout(wlv3Layout);
        wlv3Layout.setHorizontalGroup(
            wlv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wlv3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        wlv3Layout.setVerticalGroup(
            wlv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(wlv3);

        setSize(new java.awt.Dimension(1048, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void Reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_buttonActionPerformed
JOptionPane.showMessageDialog(ForgotPassword.this, "A password reset link has been sent to your email.");        // TODO add your handling code here:
    }//GEN-LAST:event_Reset_buttonActionPerformed

    private void signup_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseClicked
new Signup().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_signup_labelMouseClicked

    private void signup_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseEntered
signup_label.setFont(signup_label.getFont().deriveFont(Font.BOLD));        // TODO add your handling code here:
    }//GEN-LAST:event_signup_labelMouseEntered

    private void signup_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseExited
signup_label.setFont(signup_label.getFont().deriveFont(Font.PLAIN));        // TODO add your handling code here:
    }//GEN-LAST:event_signup_labelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FYP;
    private javax.swing.JLabel FYP_label;
    private javax.swing.JButton Reset_button;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel email_label1;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel signup_label;
    private javax.swing.JPanel wlv3;
    private javax.swing.JLabel wlvIcon;
    // End of variables declaration//GEN-END:variables
}
