/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Course_Management_System;

/**
 *
 * @author kaush
 */
public class Google extends javax.swing.JFrame {

    /**
     * Creates new form Google
     */
    public Google() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        google_panel = new javax.swing.JPanel();
        error_occured = new javax.swing.JLabel();
        google_logo = new javax.swing.JLabel();
        g_505 = new javax.swing.JLabel();
        go_back = new javax.swing.JLabel();
        internal_server = new javax.swing.JLabel();
        all_we_know = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1034, 560));
        setUndecorated(true);

        google_panel.setBackground(new java.awt.Color(255, 255, 255));
        google_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error_occured.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        error_occured.setForeground(new java.awt.Color(0, 0, 0));
        error_occured.setText("An error occurred while trying to fulfill your request .");
        google_panel.add(error_occured, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 420, 30));

        google_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ezgif.com-gif-maker.png"))); // NOI18N
        google_panel.add(google_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 340, 120));

        g_505.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        g_505.setText("505.");
        google_panel.add(g_505, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 40, 30));

        go_back.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        go_back.setForeground(new java.awt.Color(51, 102, 255));
        go_back.setText(" Go back");
        go_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_backMouseClicked(evt);
            }
        });
        google_panel.add(go_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, 30));

        internal_server.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        internal_server.setForeground(new java.awt.Color(102, 102, 102));
        internal_server.setText(" Internal server error.");
        google_panel.add(internal_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 30));

        all_we_know.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        all_we_know.setForeground(new java.awt.Color(102, 102, 102));
        all_we_know.setText("That's all we know.");
        google_panel.add(all_we_know, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(google_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(google_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1034, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void go_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_backMouseClicked
new Login().setVisible(true);
this.dispose();
    }//GEN-LAST:event_go_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Google().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel all_we_know;
    private javax.swing.JLabel error_occured;
    private javax.swing.JLabel g_505;
    private javax.swing.JLabel go_back;
    private javax.swing.JLabel google_logo;
    private javax.swing.JPanel google_panel;
    private javax.swing.JLabel internal_server;
    // End of variables declaration//GEN-END:variables
}
